language: python
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install -U setuptools pip
  - python setup.py clean --all
  - python setup.py install
script:
  - python setup.py test
matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
