[package]
name = "alohomora"
version = "0.1.0"
description = "Alohomora manages our secret distribution"

# Compatibe Python versions
python = ["^3.6"]

license = "MIT"

authors = [
    "Nemo <nemo@razorpay.com>"
]

# The readme file of the package.
#
# The file can be either README.rst or README.md.
#
# If it's a markdown file you have to install the pandoc utility
# so that it can be automatically converted to a RestructuredText file.
#
# You also need to have the pypandoc package installed.
# If you install poet via pip you can use the markdown-readme extra to do so.
readme = "README.md"

# An URL to the homepage of the project.
homepage = "https://github.com/razorpay/alohomora"
repository = "https://github.com/razorpay/alohomora"
documentation = "https://github.com/razorpay/alohomora"

# A list of keywords (max: 5) that the package is related to.
keywords = ["credstash", "ansible", "secrets", "jinja"]

# A list of patterns that will be included in the final package.

# If you packages lies elsewhere (like in a src directory),
# you can tell poet to find them from there:
# include = { from = 'src', include = '**/*' }
#
# Similarly, you can tell that the src directory represent the foo package:
include = ['alohomora/*']

# Features are sets of optional dependencies, which enhance a package,
# but are not required
# [features]
markdown-readme = ["pypandoc"] # Adds support for markdown readmes

[dependencies]
# Main dependencies of the project
# See https://github.com/sdispater/poet#dependencies-and-dev-dependencies
# toml = "^0.9"
# requests = "~2.13.0"
# cleo = { git = "https://github.com/sdispater/cleo.git", branch = "develop" }
# pathlib2 = { version = "^2.2", python = "~2.7" }
credstash = "~1.13.2"
pypandoc = { version = "^1.3.3", optional = true }
click = "~6.0.0"
jinja = "~2.9"

[dev-dependencies]
# Development dependencies of the package
# See https://github.com/sdispater/poet#dependencies-and-dev-dependencies

# CLI scripts
#
# They must follow the following convention:
# {script_name} = "{my.package:executable}"
#
# [scripts]
# alohomora = 'alohomora:app.run'